// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLeft() {
  return window['go']['main']['App']['GetLeft']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}

export function Resume() {
  return window['go']['main']['App']['Resume']();
}

export function SetDuration(arg1) {
  return window['go']['main']['App']['SetDuration'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
